services:
    app:
        image: php:8.2-alpine
        environment:
            BASE_URL: ${BASE_URL}
        working_dir: /app
        volumes:
            - .:/app
        tmpfs:
            - /tmp
    webpack:
        image: node:20-alpine
        environment:
            BASE_URL: ${BASE_URL}
        working_dir: /app
        volumes:
            - .:/app
        tmpfs:
            - /tmp
    imgproxy:
        image: darthsim/imgproxy:v3
        environment:
            - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/app
        working_dir: /app
        ports:
            - 8090:8080
        volumes:
            - .:/app:ro
        tmpfs:
            - /tmp
